# GitHub Action Workflow to deploy the frontend.

name: Deploy
on: workflow_dispatch

jobs:
  deploy_frontend:
    name: Deploy frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Git config
      run: |
        git config --local user.email "<>"
        git config --local user.name "Auto-Deploy"

    - name: Fetch GitHub data
      run: |
        git fetch --unshallow
        git checkout deploy
        git pull
        git rebase main
        git push
